DROP TABLE LOYALTY_TMP_MORE_THAN_DEMO_FACT_PTS;
DROP TABLE LOYALTY_TMP_COHORT_FINAL;
DROP TABLE LOYALTY_TMP_COHORT_IN_PERIOD;
DROP TABLE LOYALTY_TMP_FEA_CONC_TYPE;
DROP TABLE LOYALTY_TMP_COHORT_BY_AGEGRP;
DROP TABLE LOYALTY_TMP_COHORT_LONG;
DROP TABLE LOYALTY_TMP_COHORT_AGEGRP;
DROP TABLE LOYALTY_TMP_AGEGRP_PSC;
DROP TABLE LOYALTY_TMP_AGEGRP_AFC;
DROP TABLE LOYALTY_TMP_COEFF_SUMS;
DROP TABLE LOYALTY_TMP_CHARLSON_VISIT_BASE;


